"""Add comment_id to attachments

Revision ID: 7f287cbcd2ce
Revises: b7126a69a3e8
Create Date: 2026-01-19 13:12:43.056035

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f287cbcd2ce'
down_revision = 'b7126a69a3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('comment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'attachment', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='foreignkey')
    op.drop_column('attachment', 'comment_id')
    # ### end Alembic commands ###
